// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"time"
)

type TxEvent struct {
	SysCtime   time.Time `gorm:"column:sys_ctime;default:CURRENT_TIMESTAMP;NOT NULL"`
	SysUtime   time.Time `gorm:"column:sys_utime;default:CURRENT_TIMESTAMP;NOT NULL"`
	EventID    string    `gorm:"column:event_id;primary_key"`
	AppID      string    `gorm:"column:app_id;NOT NULL"`
	TopicID    string    `gorm:"column:topic_id;NOT NULL"`
	RetryCount int       `gorm:"column:retry_count;default:0;NOT NULL"`
	CbCfType   int       `gorm:"column:cb_cf_type;default:0;NOT NULL"`
	CbPtType   int       `gorm:"column:cb_pt_type;default:0;NOT NULL"`
	CbAddr     string    `gorm:"column:cb_addr;default:0;NOT NULL"`
	CbInterval int64     `gorm:"column:cb_interval"`
	CbTimeout  int64     `gorm:"column:cb_timeout"`
	TxStatus   int       `gorm:"column:tx_status;default:0;NOT NULL"`
	TxTrigger  string    `gorm:"column:tx_trigger"`
	TxMsg      string    `gorm:"column:tx_msg"`
}

func (m *TxEvent) TableName() string {
	return "tx_event"
}
